function r = miropt_pulseclarity(x)

mirchunklim(Inf)
if not(isa(x,'miraudio'))
    a = miraudio('Design'); 
else
    a = x;
end
r = mirstruct;
tot = 0;
jj = 0;
kk = 0;
ll = 0;
mm = 0;
fea = {'Pitch','Envelope'};
for n = 1:length(fea)
    if strcmpi(fea{n},'Envelope')
        nc = {'Gammatone','Scheirer','Klapuri','Spectro'};
    else
        nc = {'Pitch'};
    end
    for l = 1:length(nc)
        if strcmpi(nc{l},'Pitch')
            ft = {'Pitch'};
        elseif strcmpi(nc{l},'Spectro')
            ft = {'Spectro'};
        else
            ft = {'IIR','HalfHann'};
        end
        for j = 1:length(ft)
            ll = ll+1;
            if strcmpi(nc{l},'Pitch')
                r.tmp.onsets{ll} = mironsets(a,'Diff',0,'Pitch',...
                            'Sum',0,'Detect',0);
            elseif strcmpi(nc{l},'Spectro')
                r.tmp.onsets{ll} = mironsets(a,'Diff',0,...
                            'Method','Spectro','UpSample',...
                            'Sum',0,'Detect',0,'Filterbank',0);
            elseif strcmpi(ft{j},'IIR')
                r.tmp.onsets{ll} = mironsets(a,'Diff',0,...
                            'FilterbankType',nc{l},'Filterbank',20,...
                            'Envelope','Sum',0,'Detect',0);
            else
                r.tmp.onsets{ll} = mironsets(a,'Diff',0,...
                            'FilterbankType',nc{l},'Filterbank',20,...
                            'FilterType','HalfHann','PreDecim',180,...
                            'Envelope','Sum',0,'Detect',0);
            end
            r.tmp.logonsets{ll} = ...
                mironsets(r.tmp.onsets{n},'Log','Detect',0);
            if strcmpi(nc{l},'Pitch')
                su = {'After'};
                llg = 1;
                order = 1;
                hwr = 1;
            else
                llg = 1:2;
                order = [1 8];
                hwr = [0 .8 1];
                if strcmpi(nc{l},'Scheirer')
                    su = {'Before','After'};
                else
                    su = {'Before','Adjacent','After'};
                end
            end
            for hw = 1:length(hwr)
                for lg = 1:length(llg)
                    for o = 1:length(order)
                        mm = mm+1;
                        if llg(lg) == 2
                            logonsets = r.tmp.logonsets{ll};
                        else
                            logonsets = r.tmp.onsets{ll};
                        end
                        if hw>1
                            r.tmp.modifonsets{mm} = ...
                                mironsets(logonsets,...
                                    'HalfwaveDiff',order(o),...
                                    'Lambda',hwr(hw),...
                                    'Sum',0,'Detect',0);
                        else
                            r.tmp.modifonsets{mm} = ...
                                mironsets(logonsets,...
                                    'Diff',order(o),...
                                    'Sum',0,'Detect',0);
                        end
                        for m = 1:length(su)
                            jj = jj+1;
                            [r.fea{n}.nc{l}.ft{j}.ord{o}.log{lg}.hwr{hw}...
                                .res{1}.su{m}.max r.tmp.ac{jj}] = ...
                                mirpulseclarity(r.tmp.modifonsets{mm},...
                                     'Enhanced',0,'Resonance',0,...
                                     'Sum',su{m},'MaxAutocor');
                            res = {0,'ToiviainenSnyder','vonNoorden'};
                            for k = 1:length(res)
                                kk = kk+1;
                                r.tmp.ac2{kk} = mirautocor(r.tmp.ac{jj},...
                                                    'Resonance',res{k});
                                if k > 1
                                    r.fea{n}.nc{l}.ft{j}.ord{o}.log{lg}...
                                        .hwr{hw}.res{k}.su{m}.max = ...
                                        mirpulseclarity(r.tmp.ac2{kk},...
                                            'MaxAutocor');
                                end
                                r.fea{n}.nc{l}.ft{j}.ord{o}.log{lg}...
                                    .hwr{hw}.res{k}.su{m}.min = ...
                                    mirpulseclarity(r.tmp.ac2{kk},...
                                            'MinAutocor');
                                r.fea{n}.nc{l}.ft{j}.ord{o}.log{lg}...
                                    .hwr{hw}.res{k}.su{m}.kurtosis = ...
                                    mirpulseclarity(r.tmp.ac2{kk},...
                                            'KurtosisAutocor','Total',1);
                                r.fea{n}.nc{l}.ft{j}.ord{o}.log{lg}...
                                    .hwr{hw}.res{k}.su{m}.entropy0 = ...
                                    mirpulseclarity(r.tmp.ac2{kk},...
                                            'EntropyAutocor');
                                r.fea{n}.nc{l}.ft{j}.ord{o}.log{lg}...
                                    .hwr{hw}.res{k}.su{m}.interf0 = ...
                                    mirpulseclarity(r.tmp.ac2{kk},...
                                            'InterfAutocor','Total',Inf);

                                r.tmp.ac3{kk} = mirautocor(r.tmp.ac2{kk},...
                                                    'Enhanced');
                                r.fea{n}.nc{l}.ft{j}.ord{o}.log{lg}...
                                    .hwr{hw}.res{k}.su{m}.entropy1 = ...
                                    mirpulseclarity(r.tmp.ac3{kk},...
                                            'EntropyAutocor');
                                r.fea{n}.nc{l}.ft{j}.ord{o}.log{lg}...
                                    .hwr{hw}.res{k}.su{m}.interf = ...
                                    mirpulseclarity(r.tmp.ac3{kk},...
                                            'InterfAutocor','Total',Inf);
                                r.fea{n}.nc{l}.ft{j}.ord{o}.log{lg}...
                                    .hwr{hw}.res{k}.su{m}.tempo = ...
                                    mirpulseclarity(r.tmp.ac3{kk},...
                                            'TempoAutocor');
                                tot = tot+6;
                            end
                        end
                        if strcmpi(fea{n},'Envelope') && hw == 1 && lg == 1
                            r.tmp.sumdiffonsets{mm} = ...
                                mironsets(mirsum(...
                                    mironsets(r.tmp.modifonsets{mm})),...
                                          'Detect','Contrast',.3);
                            %r.tmp.sumdiffonsets{mm},drawnow
                            r.fea{n}.nc{l}.ft{j}.ord{o}.attack = ...
                                mirpulseclarity(r.tmp.sumdiffonsets{mm},...
                                                    'AttackDiff');
                        else
                            r.tmp.sumdiffonsets{mm} = r.tmp.modifonsets{mm};
                        end
                    end
                end
            end
            if strcmpi(fea{n},'Envelope')
                r.tmp.sumonsets{ll} = mironsets(mirsum(r.tmp.onsets{ll}),...
                                                'Detect','Contrast',.3);
                %r.tmp.sumonsets{ll},drawnow
                r.fea{n}.nc{l}.ft{j}.xtrem = ...
                    mirpulseclarity(r.tmp.sumonsets{ll},'ExtremEnvelop');
                r.fea{n}.nc{l}.ft{j}.attack = ...
                    mirpulseclarity(r.tmp.sumonsets{ll},'Attack','Diff');
                r.fea{n}.nc{l}.ft{j}.attack2 = ...
                    mirpulseclarity(r.tmp.sumonsets{ll},'Attack','Gauss');
            else
                r.tmp.sumonsets{ll} = r.tmp.onsets{ll};
            end
        end
    end
end
r.artic = mirpulseclarity(a,'Articulation');
drawnow

if not(isa(x,'miraudio'))
    r = mireval(r,x,'Single','pcpred.txt');
end

%mirexport('pulseclarity_predict.txt',r);